name: elea_mobile
description: "Flutter Audio Recorder and Transcription App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  audio_waveforms: ^1.0.5
  permission_handler: ^11.3.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  intl: ^0.19.0
  stream_transform: ^2.1.0
  dio: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true